/* 
 * POSTGRECR - MARC-HI CLIENT REGISTRY SEARCH FUNCTIONS FOR POSTGRESQL
 * VERSION: 2.0
 * AUTHOR: JUSTIN FYFE
 * DATE: JULY 12, 2012
 * FILES:
 *	POSTGRECR-DDL.SQL	- SQL CODE TO CREATE TABLES, INDECIES, VIEWS AND SEQUENCES
 *	POSTGRECR-SRCH.SQL	- SQL CODE TO CREATE SEARCH FUNCTIONS
 *	POSTGRESHR-FX.SQL	- SQL CODE TO CREATE SUPPORT PROCEDURES AND FUNCTIONS
 * DESCRIPTION:
 *	THIS FILE CLEANS AND THEN RE-CREATES THE POSTGRESQL CLIENT REGISTRY
 *	DATABASE SCHEMA INCLUDING TABLES, VIEWS, INDECIES AND SEQUENCES. 
 * LICENSE:
 * 	Licensed under the Apache License, Version 2.0 (the "License");
 * 	you may not use this file except in compliance with the License.
 * 	You may obtain a copy of the License at
 *
 *     		http://www.apache.org/licenses/LICENSE-2.0
 *
 * 	Unless required by applicable law or agreed to in writing, software
 * 	distributed under the License is distributed on an "AS IS" BASIS,
 * 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * 	See the License for the specific language governing permissions and
 * 	limitations under the License.
 */

-- @FUNCTION 
-- FIND NAME COMPONENTS WITH A SIMILAR SOUNDING PARTS
CREATE OR REPLACE FUNCTION FIND_NAME_CMP_LIKE (
	NAME_VALUE_IN		IN VARCHAR(256),
	NAME_CMP_CLS_IN		IN DECIMAL(4),
	NAME_MIN_MATCH_IN	IN DECIMAL(1)
) RETURNS TABLE 
(
	NAME_SET_ID 	DECIMAL,
	SCORE 		INT
) 
AS
$$
BEGIN
	RETURN QUERY SELECT NAME_CMP_TBL.NAME_SET_ID, DIFFERENCE(NAME_VALUE_IN, NAME_CMP_VALUE) FROM NAME_CMP_TBL 
		WHERE DIFFERENCE(NAME_VALUE_IN, NAME_CMP_VALUE) >= NAME_MIN_MATCH_IN AND
			NAME_CMP_CLS = NAME_CMP_CLS_IN;
END;
$$ LANGUAGE plpgsql;

-- @FUNCTION
-- FIND NAME SETS
CREATE OR REPLACE FUNCTION FIND_PSN_BY_NAME_SET(
	NAME_CMP_VAL_IN	IN VARCHAR[],
	NAME_CMP_CLS_IN IN DECIMAL[],
	NAME_MIN_MATCH_IN IN DECIMAL(1),
	NAME_SET_USE_IN	IN DECIMAL(20)
) RETURNS TABLE (PSN_ID DECIMAL(20,0)) AS
$$
DECLARE
	CNCMP			DECIMAL;
	TMP_NAME_RET_TBL	DECIMAL[];
	TMP_NAME_RES_TBL	DECIMAL[];
BEGIN



	-- FILTER THE FIRST SET
	TMP_NAME_RET_TBL := ARRAY(SELECT A.NAME_SET_ID 
		FROM NAME_CMP_TBL A 
		WHERE
			(
				DIFFERENCE(NAME_CMP_VALUE, NAME_CMP_VAL_IN[1]) >= NAME_MIN_MATCH_IN OR
				(NAME_CMP_CLS_IN[1] = 1 AND NAME_CMP_VALUE IN (SELECT SYN_NAME FROM NAME_CMP_SYN_CDTBL WHERE DIFFERENCE(PRI_NAME, NAME_CMP_VAL_IN[1]) >= NAME_MIN_MATCH_IN)) OR
				(NAME_CMP_CLS_IN[1] = 1 AND NAME_CMP_VALUE IN (SELECT PRI_NAME FROM NAME_CMP_SYN_CDTBL WHERE DIFFERENCE(SYN_NAME, NAME_CMP_VAL_IN[1]) >= NAME_MIN_MATCH_IN))
			)
		AND
			NAME_CMP_CLS = NAME_CMP_CLS_IN[1]);

	-- SUBSEQUENT
	IF(ARRAY_LOWER(NAME_CMP_VAL_IN, 1) < ARRAY_UPPER(NAME_CMP_VAL_IN, 1)) THEN
		FOR CNCMP IN ARRAY_LOWER(NAME_CMP_VAL_IN, 1) + 1 .. ARRAY_UPPER(NAME_CMP_VAL_IN, 1) LOOP
			TMP_NAME_RET_TBL := ARRAY(
				SELECT A.NAME_SET_ID 
				FROM NAME_CMP_TBL A
				WHERE
					(
						DIFFERENCE(NAME_CMP_VALUE, NAME_CMP_VAL_IN[CNCMP]) >= NAME_MIN_MATCH_IN OR
						(NAME_CMP_CLS_IN[CNCMP] = 1 AND NAME_CMP_VALUE IN (SELECT SYN_NAME FROM NAME_CMP_SYN_CDTBL WHERE DIFFERENCE(PRI_NAME, NAME_CMP_VAL_IN[CNCMP]) >= NAME_MIN_MATCH_IN)) OR
						(NAME_CMP_CLS_IN[CNCMP] = 1 AND NAME_CMP_VALUE IN (SELECT PRI_NAME FROM NAME_CMP_SYN_CDTBL WHERE DIFFERENCE(SYN_NAME, NAME_CMP_VAL_IN[CNCMP]) >= NAME_MIN_MATCH_IN))
					)
				AND
					NAME_CMP_CLS = NAME_CMP_CLS_IN[CNCMP]
				AND 
					A.NAME_SET_ID = ANY (TMP_NAME_RET_TBL));

		END LOOP;
	END IF;
	
	RETURN QUERY SELECT PSN_NAME_SET_TBL.PSN_ID FROM PSN_NAME_SET_TBL WHERE 
		PSN_NAME_SET_TBL.NAME_SET_ID = ANY (TMP_NAME_RET_TBL) 
			AND
		(NAME_SET_USE_IN IS NOT NULL AND NAME_SET_USE = NAME_SET_USE_IN OR NAME_SET_USE_IN IS NULL) 
			AND
		OBSLT_VRSN_ID IS NULL;
END;
$$ LANGUAGE plpgsql;

