/** 
 * CLIENT REGISTRY VERSION 1.2 UPGRADE SCRIPT
 */


 -- @FUNCTION
-- GET DATABASE SCHEMA VERSION
--
-- RETURNS: THE MAJOR, MINOR AND RELEASE NUMBER OF THE DATABASE SCHEMA
CREATE OR REPLACE FUNCTION GET_SCH_VER() RETURNS VARCHAR AS
$$
BEGIN
	RETURN '1.2.0.0';
END;
$$ LANGUAGE plpgsql;

-- @PROCEDURE
-- PUSH A QUERY RESULT INTO A RESULT SET
CREATE OR REPLACE FUNCTION PUSH_QRY_RSLTS
(
	QRY_ID_IN	IN VARCHAR(128),
	RSLT_ENT	IN VARCHAR
) RETURNS VOID AS 
$$
DECLARE
	RSLT_ENT_ID_ARR DECIMAL[][];
BEGIN

	
	RSLT_ENT_ID_ARR := RSLT_ENT;
	FOR RSLT IN ARRAY_LOWER(RSLT_ENT_ID_ARR, 1) + 0 .. ARRAY_UPPER(RSLT_ENT_ID_ARR, 1) LOOP

		INSERT INTO QRY_RSLT_TBL (ENT_ID, QRY_ID, VRSN_ID)
			VALUES (RSLT_ENT_ID_ARR[RSLT][1], QRY_ID_IN, RSLT_ENT_ID_ARR[RSLT][2]);

	END LOOP;

	RETURN;
END
$$
LANGUAGE PLPGSQL;